include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/application/ui/themes/app_icons_icons.dart

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    use_build_context_synchronously: false

    # Правила, связанные с const
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_constructors_in_immutables: true

    # Правила, связанные с импортами
    directives_ordering: true
    # Запрещает относительные импорты внутри lib, принуждая использовать полные (package:) импорты.
    avoid_relative_lib_imports: true

    # Правила для var и final
    # Использование var вместо явного указания типа, когда тип может быть выведен.
    omit_local_variable_types: true
    # Использование final вместо var, если переменной не происходит переназначение.
    prefer_final_locals: true
