name: example
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  stun_kit:
    path: ../
  auto_route: ^9.2.2
  provider: ^6.1.2
  cupertino_icons: ^1.0.8

  lazy_load_scrollview: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^9.0.0
  build_runner:

flutter:
  uses-material-design: true
  assets:
     - .env