name: stun_kit
description: A Flutter package with common architectural classes to simplify app development and organization.
version: 0.0.1
homepage: https://stun-apps.com/
repository: https://github.com/STUN-Apps-Dev/stun_kit
issue_tracker: https://github.com/STUN-Apps-Dev/stun_kit/issues

environment:
  sdk: ">=2.19.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_dotenv: ^5.2.1
  appmetrica_plugin: ^3.1.0
  bugsnag_flutter: ^4.1.0
  logger: ^2.5.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
